sonata_admin:
    title: Admin
    options:
        html5_validate: true
    security:
        handler: sonata.admin.security.handler.noop
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            Users:
                label: Users
                items:
                    - App\Admin\UserAdmin

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
